CONFIG_ROOMS = "Rooms"
CONFIG_ROOM_NAME = "Name"
CONFIG_ROOM_POINTS = "Points"

CONFIG_POINT_NAME = "Name"
CONFIG_POINT_TYPE = "Type"
CONFIG_POINT_TYPE_LIGHT = "Light"
CONFIG_POINT_CONTROLPIN = "GpioControlPin"
CONFIG_POINT_BUTTONPIN = "GpioButtonPin"

NAME_SEPARATOR = "/"