CONFIG_GENERAL = "General"
CONFIG_GENERAL_NAME = "Name"

CONFIG_CONNECTIVITY = "Connectivity"
CONFIG_CONNECTIVITY_CLIENTNAME = "ClientName"
CONFIG_CONNECTIVITY_MQTTIP = "MqttIp"
CONFIG_CONNECTIVITY_MQTTPORT = "MqttPort"

CONFIG_ROOMS = "Rooms"
CONFIG_ROOM_NAME = "Name"
CONFIG_ROOM_POINTS = "Points"

CONFIG_POINT_NAME = "Name"
CONFIG_POINT_TYPE = "Type"
CONFIG_POINT_TYPE_LIGHT = "Light"
CONFIG_POINT_TYPE_BLIND = "Blind"
CONFIG_POINT_CONTROLPIN = "GpioControlPin"
CONFIG_POINT_BUTTONPIN = "GpioButtonPin"

NAME_SEPARATOR = "/"
TOPIC_IN = "In"
TOPIC_OUT = "Out"
TOPIC_ADMIN = "Admin"

COMMAND_ON = "ON"
COMMAND_OFF = "OFF"
COMMAND_RESET = "RESET"
COMMAND_NOTIFY_CURRENT_STATE = "NOTIFY_CURRENT_STATE"
COMMAND_OPEN = "STATE_OPEN"
COMMAND_1_4 = "STATE_1/4"
COMMAND_1_2 = "STATE_1/2"
COMMAND_3_4 = "STATE_3/4"
COMMAND_CLOSED = "STATE_CLOSED"

POSITION_OPEN = 0
POSITION_1_4 = 25
POSITION_1_2 = 50
POSITION_3_4 = 75
POSITION_CLOSED = 100