CONFIG_GENERAL = "General"
CONFIG_GENERAL_NAME = "Name"

CONFIG_CONNECTIVITY = "Connectivity"
CONFIG_CONNECTIVITY_CLIENTNAME = "ClientName"
CONFIG_CONNECTIVITY_MQTTIP = "MqttIp"
CONFIG_CONNECTIVITY_MQTTPORT = "MqttPort"

CONFIG_ROOMS = "Rooms"
CONFIG_ROOM_NAME = "Name"
CONFIG_ROOM_POINTS = "Points"

CONFIG_POINT_NAME = "Name"
CONFIG_POINT_TYPE = "Type"
CONFIG_POINT_TYPE_LIGHT = "Light"
CONFIG_POINT_CONTROLPIN = "GpioControlPin"
CONFIG_POINT_BUTTONPIN = "GpioButtonPin"

NAME_SEPARATOR = "/"
TOPIC_IN = "In"
TOPIC_OUT = "Out"

COMMAND_ON = "ON"
COMMAND_OFF = "OFF"